apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
  labels:
    app: task-management-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task-management-system
  template:
    metadata:
      labels:
        app: task-management-system
    spec:
      containers:
      - name: application
        image: ashish07860/task-management-system:1.0
        ports:
        - containerPort: 80

