apiVersion: v1
kind: Service
metadata:
  name: application-service
spec:
  type: LoadBalancer
  selector:
    app: task-management-system
  ports:
    - protocol: TCP
      port: 8787
      targetPort: 80
